apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  destination:
    namespace: jellyfin
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./kubernetes/generated/medium-format/jellyfin
    repoURL: https://github.com/achernya/homelab.git
    targetRevision: nixidy
  syncPolicy: {}
