apiVersion: v2
name: jellyfin
description: Jellyfin
type: application
# Follows semver, must be updated every time this chart is modified.
version: 0.0.1
# Version of the application, for display. Does not have to follow semver.
appVersion: "0.0.1"

dependencies:
  - name: jellyfin
    version: 2.3.0
    repository: https://jellyfin.github.io/jellyfin-helm
